### ISSUE TITLE
More relaxed rendering of vocabulary for visualization

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#26]
In order to visualize the Alignment tool requires (for SKOS) ConceptScheme to be included and presence of both taxonomical relationship i.e. broader must be accompanied with narrower etc. It would be good not to insist on all taxonomical (redundant) information.

E.g. the Alignment tool cannot visualize codelist, https://github.com/openbudgets/datasets/blob/master/ESF-CZ/2007-2013/projects/codelists/esf_2007_2013_czech_operational_programmes.ttl

**Comment by skarampatakis** [comment]
Fixed for skos vocabularies. However I noticed that there were entities with no labels. Now the UI fallbacks to shorten IRIs if no label is found. A more sophisticated way to construct the tree will be implemented in future releases following [this ](http://labs.sparna.fr/skos-play/about) approach .
