### ISSUE TITLE
Error when validating RDF-file

### ISSUE THREAD

**Issue by schmaluk** [okgreece/Alignment#27]
I have uploaded this RDF-file as New Graph:
<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:si="http://www.w3schools.com/rdf/">
<rdf:Description rdf:about="http://www.w3schools.com">
  <si:title>W3Schools</si:title>
  <si:author>Jan Egil Refsnes</si:author>
</rdf:Description>
</rdf:RDF>

![alignment_error](https://cloud.githubusercontent.com/assets/17597578/21856952/0c13f5a6-d824-11e6-9c1b-a0e4ea662b13.PNG)
When validating, Im getting this:
![alignment_error2](https://cloud.githubusercontent.com/assets/17597578/21857010/40e5d4a2-d824-11e6-8cd0-32250680f7d2.PNG)

Maybe this has sthg to do that on the server php7 is running and not 5(?)

**Comment by skarampatakis** [comment]
I have test it with php7 as well. Our server on alignment.okfn.gr runs on php7.

Maybe it is related to [this](https://gitlab.com/davical-project/davical/issues/91)

Can you please do a 
```
sudo apt-get install php7.0-xml
```

and inform if it is fixed? I will update then requirements.

**Comment by schmaluk** [comment]
Yes that has helped. Thanks.
Now Im getting an error when trying to execute a Project:
![alignment-error4](https://cloud.githubusercontent.com/assets/17597578/21861154/f884c028-d833-11e6-8960-069e56def659.PNG)
![alignment-error3](https://cloud.githubusercontent.com/assets/17597578/21861159/fb85f85a-d833-11e6-8870-d1bf2af23788.PNG)
I have these libraries loaded:
- libgd3 
- php7.0-gd 
- libapache2-mod-php7.0 
- php7.0-xml 
- php7.0-json 
- php7.0-xsl 
- php7.0-redis 
- php7.0-mcrypt
- php7.0-imagick 
- php7.0-common 
- php7.0-zip
Im getting the same error also on your server: http://alignment.okfn.gr

**Comment by skarampatakis** [comment]
This is related to #26. Please try to get your tests with some of the codelists we have on Code-list repo.
