### ISSUE TITLE
Suggestions for better control (after an initial testing with domain expert)

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#28]
Most of the following points relate to the fact that people (domain experts) need more information in the GUI:
* it would be good to show some pop up help for individual buttons in the tool when one move over them (e.g. "create SiLK configuration etc.")
* it would be good to show users names who uploaded the file and created the project (this is helpful e.g. for communication)
* what about to enable importing existing links to show them in "MyLinks"?
* after creation of the link it would be better to also show prefLabel otherwise it is not easy to see what concept mean
* created links are not properly named when there is dot in name e.g. http://example/A.12 is shortened to ns0:12 (missing A.)
* for smoother navigation in the target graph it would be good to somehow annotate (with color or symbol) which concepts have some similarity scores computed
* for smoother navigation in the target graph it would be good to somehow annotate (with color or symbol) which concepts have already been linked
* for the domain expert it was a little bit confusing to see written "graph" (e.g. source graph). Perhaps, it would be good to write that it can be any kind of ontology (vocabulary, codelist etc.)
* regarding mapping properties it would need more information to provide. The domain expert did not understand e.g. "owl:sameAs". Perhaps, it would be good to add some explanation. And as I wrote before, it would need to add more mapping properties.
* we encounter on interesting situation. The domain expert was working under her account and she was created several links in the project I created in my account. Created links were not visible in "My Links" in her account but in my account. It seems as a bug or it is an intention?
* there is already option to export created links, however it seems that people would also want to have an option to export to csv format.
* we were further discussing the usage of Alignment for collaborative working of more domain experts. "My votes" functionality should support this but it would need to be more structured e.g. according to projects and also people would need more information to understand all information (e.g. using prefLabel in the skos case etc.). We realized that if more domain experts would work on one project it would not be possible to add one link several times (only the first user can add it into shared project) which would be necessary when more domain experts work on creation of reference linkset. This could be solved by interweaving it with "My votes" functionality. But perhaps you consider some other workflow supporting such a scenario.

Ondrej

**Comment by skarampatakis** [comment]
Most if not all of these suggestions are included in latest master branch.
