### ISSUE TITLE
Ability to import existing links on project.  

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/Alignment#31]
As suggested on #28 It could be useful if a user could bulk upload existing links on a project. Then, links could be shown up on MyLinks page and on Voting Page. Perhaps a useful addition could be the ability to create a vote only project type.

**Comment by OndrejZamazal** [comment]
Vote only project type is a good solution. I saw that it is already included in My projects page. Is there already also import option somewhere? It seems to me that this is future work. I cannot find it.

**Comment by skarampatakis** [comment]
Import option implemented. It can be found on my links page. You can import links in various RDF serializations to a specific project. Triples must follow the pattern <source_entity> <link> <target_entity> in as these are defined on the project. Vote only option is not yet implemented, it will by the end of the week, as feedback from the last workshop showed there is a good use case here.
