### ISSUE TITLE
Annotate (with color or symbol) which concepts have already been linked or have some similarity scores computed

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/Alignment#34]
As suggested on #28 

* for smoother navigation in the target graph it would be good to somehow annotate (with color or symbol) which concepts have some similarity scores computed
* for smoother navigation in the target graph it would be good to somehow annotate (with color or symbol) which concepts have already been linked

That would require modification of d3.js script. Must be tested for performance issues, because would require updating both graphs multiple times. 

Current color scheme:
* blue - element containing children.
* orange - element does not contain children
* green - selected element
* purple - selected element path to root

My opinion is on adding symbols as adding colors would make interface a bit complex. Simple icons would be probably better choice. Will be tested for both.

**Comment by OndrejZamazal** [comment]
Symbols sound like a good choice.

**Comment by skarampatakis** [comment]
Linked entities are annotated with a green circle on the left. We are planning a new graph renderer as it seems d3.js has low performance dealing with large graphs (over 10k nodes) that will allow more flexibility on this issue and other capabilities also.
