### ISSUE TITLE
Mention to "graph" seems to be confusing on UI

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/Alignment#35]
The more generic meaning of "graph" seems to be confusing sometimes as suggested on #28. Perhaps either omit the word where it is mentioned, or replace it with something else.  

> for the domain expert it was a little bit confusing to see written "graph" (e.g. source graph). Perhaps, it would be good to write that it can be any kind of ontology (vocabulary, codelist etc.)

what would be the alternatives here?

**Comment by OndrejZamazal** [comment]
What about to use general notion "ontology" (source and target ontology)? Or "vocabulary", but "ontology" is more general.

**Comment by skarampatakis** [comment]
Changed mentions of "graph" to more general "ontology".
