### ISSUE TITLE
Switch to Protocol relatives Urls for assets, links instead of absolute paths in Alignment

### ISSUE THREAD

**Issue by schmaluk** [okgreece/Alignment#38]
In order to serve the Alignment app also via **https** it might be good, if the URLs of the assets (css, js and other links) are at least **protocol relative** instead of absolute paths. https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by skarampatakis** [comment]
Relative paths are used already, utilizing the asset() helper function, which constructs the correct link based on the requested scheme. I have tested it locally with Apache and it works out of the box as you can see below.

![image](https://cloud.githubusercontent.com/assets/2419820/22120439/59f7d9e4-de88-11e6-98e7-37a369c63ed6.png)

Perhaps this is an issue with proxy as discussed [here](https://github.com/laravel/framework/issues/2171#issuecomment-51594865)

I have checked and there is no X-Forwarded-Proto header on the response header so maybe that's the issue. 

Maybe [this](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-load-balancing-with-ssl-termination) helps.

**Comment by skarampatakis** [comment]
Any update on this?

**Comment by schmaluk** [comment]
Not yet. Sorry.

**Comment by skarampatakis** [comment]
You have not tested or it is not working?

**Comment by schmaluk** [comment]
I have tested it already but without the CSS, JS-links working. I tried to pass the request via http to apache from nginx. Probably I need to enable https for the apache and pass the request to apache via https from nginx.

**Comment by skarampatakis** [comment]
OK, please inform on any update. This seems not to be related with the app but with the server configuration as I can not reproduce it.
