### ISSUE TITLE
Silk does not compute similarities when TriG format is used

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#39]
New project for linking can be made for TriG files but Silk does not compute similarities due to the missing graph specification. This should be added into the configuration parameters. 

However, I remember that the configuration for Silk will be improved in future. 

This could be solved by enabling configuration import as mentioned in #4. Is there any news about it?

**Comment by skarampatakis** [comment]
Should be fixed by importing silk configuration file with the graph name parameter
