### ISSUE TITLE
Alternative options to show at My Votes page for entities in links

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#50]
There are displayed identifiers for entities at My Votes page. I wonder whether it would be possible to select option of displaying prefLabel instead similarly as it is used at My Projects page for created links?

This would enable better usage for experts who need to see more meaningful description.

Further, it seems that a preview option does not work well since there is always only full identifier instead of RDF snippet. Such RDF snippet would also help experts to use My Vote functionality better.

Thank you
Ondrej

**Comment by skarampatakis** [comment]
Current My Votes view needs a per project filter. When it is in place I can load just the two graphs and get the labels. At the moment it shows all votes from all projects so it would require to load all graphs -> huge scalability issues. The preview popover dereferences the IRI. If it is available it will show the RDF snippet that describes the resource. It can be changed to use the already available (or merge) info from the uploaded graph, once I have implemented the filter. Are there any better ideas? I am thinking of setting up a local triplestore but I am afraid of scalability issues.

**Comment by OndrejZamazal** [comment]
Regarding the first part of your answer, I had in mind the situation where one must select the project, so there are not all graphs in play. But now I see that there is new functionality which enables something like this. Thanks

Regarding the second part of your answer, I thought that information from an uploaded graph could be used as you wrote. I did not realize that it would cause scalability issue. I have no better idea about this now.

**Comment by skarampatakis** [comment]
Merged My votes view with Votes. On project selection you get a view of all your votes on the particular project allong with title and a preview. Some improvements will follow, showing your exact vote by color.
