### ISSUE TITLE
Removing my links from project of somebody else

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#51]
We encountered on a situation which is probably not in line with envisioned usage. I created the project for linking by one domain expert. Thus I am owner of the project but the links were created by another user. Domain expert wanted to remove some of his links at "My Links" but he reported to me that he cannot select any project and thus he cannot see any his links. I think that this situation (links of somebody else in my project) is not expected but I had to prepare the project for the domain expert. Is there a way how one could remove his own links by himself even if they are in project of someone else?

Thanks
Ondrej

**Comment by skarampatakis** [comment]
Fixed on the recent commit. Please check. On the "Create Links" view, the table will show all created links by all users for the project. However a user can delete a link only if is the owner of the project or the creator of the link. On the "My links" view only links created by the user will be shown, included those created on public projects. 

A question: Does a more expressive user management system makes sense? I think that groups may have some usability in the app generally. It is something missing on my opinion.
