### ISSUE TITLE
Downloadable ontologies from 'My Ontologies'

### ISSUE THREAD

**Issue by OndrejZamazal** [okgreece/Alignment#57]
I would say that it would make sense to enable a possibility to download any ontology from 'My Ontologies' which are owned by the user or are public ones. File name could be the link to the source code of ontology. What do you think about this?

Ondrej

**Comment by skarampatakis** [comment]
Hi Ondrej,
I have no objection on this. The output should be the same as the original or would you like the option to have it converted in other serializations also?

**Comment by OndrejZamazal** [comment]
Hi Sotiris,
I think that the option to select preferred serialization would be great.
Thanks

**Comment by skarampatakis** [comment]
Now you can download the ontologies on several different serializations.
